In [2]:
import numpy as np
import pandas as pd

In [2]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print(arr_1d)

1D Array:
[1 2 3 4 5]


In [3]:
# 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:")
print(arr_2d)


2D Array:
[[1 2 3]
 [4 5 6]]


In [4]:
arr_multi = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr_multi)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [5]:
zeros_arr = np.zeros((3, 3))
print(zeros_arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
ones = np.ones((2,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [8]:
random = np.random.random((2, 2))
print(random)

[[0.40125538 0.72121558]
 [0.61013826 0.72745922]]


In [14]:
range = np.arange(0,10,2) #2 is step here
print(range)
# Create a 1D array with 12 elements
range2=np.arange(12)
print(range2)

[0 2 4 6 8]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [11]:
linspace = np.linspace(0, 5, 10) # 10 is no. of values 
print(linspace)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [13]:
random_int_arr = np.random.randint(1, 100, (2, 6))
print(random_int_arr)

[[69  9 76 18 34 96]
 [72 48 98 96 77 67]]


In [21]:
a = np.arange(10,50,5)
print(a)

[10 15 20 25 30 35 40 45]


In [24]:
b = a.reshape(2,4)
print(b)

[[10 15 20 25]
 [30 35 40 45]]


# RESHAPING AND RESIZING 

In [3]:
# Create a 1D array
arr_1d = np.arange(1, 7)  # [1, 2, 3, 4, 5, 6]

# Reshape the 1D array into a 2D array
arr_2d = arr_1d.reshape(2, 3)
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [4]:
# Create a 1D array
arr_1d = np.array([1, 2, 3, 4, 5])

# Resize the array to have 8 elements
arr_1d.resize(8)
print(arr_1d)

[1 2 3 4 5 0 0 0]


In [5]:
# Create a 2D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6]])

# Flatten the 2D array
arr_flat = arr_2d.flatten()
print(arr_flat)

[1 2 3 4 5 6]


In [6]:
import numpy as np

# Create a 2D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6]])

# Flatten the 2D array using ravel()
arr_flat = np.ravel(arr_2d)
print("Flattened 2D array:")
print(arr_flat)

Flattened 2D array:
[1 2 3 4 5 6]


# Array Concatenation and Splitting

In [7]:
import numpy as np

# Create two 2D arrays
arr1 = np.array([[1, 2],
                 [3, 4]])

arr2 = np.array([[5, 6]])

# Concatenate along axis 0 (rows)
concatenated_rows = np.concatenate((arr1, arr2), axis=0)
print("Concatenated along axis 0 (rows):")
print(concatenated_rows)

# Concatenate along axis 1 (columns)
concatenated_columns = np.concatenate((arr1, arr2.T), axis=1)
print("\nConcatenated along axis 1 (columns):")
print(concatenated_columns)


Concatenated along axis 0 (rows):
[[1 2]
 [3 4]
 [5 6]]

Concatenated along axis 1 (columns):
[[1 2 5]
 [3 4 6]]


In [8]:
# Create two 1D arrays
arr3 = np.array([1, 2])
arr4 = np.array([3, 4])

# Vertically stack arrays (concatenate along axis 0)
concatenated_vertically = np.vstack((arr3, arr4))
print("Vertically concatenated arrays:")
print(concatenated_vertically)

# Horizontally stack arrays (concatenate along axis 1)
concatenated_horizontally = np.hstack((arr3, arr4))
print("\nHorizontally concatenated arrays:")
print(concatenated_horizontally)


Vertically concatenated arrays:
[[1 2]
 [3 4]]

Horizontally concatenated arrays:
[1 2 3 4]


In [9]:
# Create a 1D array
arr5 = np.array([1, 2, 3, 4, 5, 6])

# Split the array into three equal-sized arrays
split_result = np.split(arr5, 3)
print("Split array into three parts:")
print(split_result)


Split array into three parts:
[array([1, 2]), array([3, 4]), array([5, 6])]


In [10]:
# Create a 2D array
arr6 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

# Vertically split the array into two parts
vertical_split = np.vsplit(arr6, 3)
print("Vertically split array:")
print(vertical_split)

# Horizontally split the array into three parts
horizontal_split = np.hsplit(arr6, 3)
print("\nHorizontally split array:")
print(horizontal_split)


Vertically split array:
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

Horizontally split array:
[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


# Universal Functions (ufuncs)

In [1]:
import numpy as np

# Create two arrays
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

# Addition
print(np.add(arr1, arr2))  # Equivalent to arr1 + arr2

# Subtraction
print(np.subtract(arr1, arr2))  # Equivalent to arr1 - arr2

# Multiplication
print(np.multiply(arr1, arr2))  # Equivalent to arr1 * arr2

# Division
print(np.divide(arr1, arr2))  # Equivalent to arr1 / arr2

# Exponentiation
print(np.power(arr1, 2))  # Equivalent to arr1 ** 2


[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[ 1  4  9 16]


Bitwise Functions: These functions operate bitwise on integer arrays.

np.bitwise_and()
np.bitwise_or()
np.bitwise_xor()
np.bitwise_not()

Special Functions: These functions include mathematical special functions like gamma, error, and hyperbolic functions.

np.gamma()
np.erf()
np.arcsinh()

Rounding Functions: These functions round elements of an array to the nearest integer or to a specified number of decimals.

np.round()
np.floor()
np.ceil()

Statistical Functions: These functions compute statistical measures like mean, median, standard deviation, variance, and more.

np.mean()
np.median()
np.std()
np.var()

Array Comparison Functions: These functions compare arrays element-wise and return boolean arrays indicating the result of the comparison.

np.isclose()
np.allclose()

Logical Functions: These functions perform logical operations on arrays.

np.logical_and()
np.logical_or()
np.logical_not()

# BROADCASTING

 Broadcasting is a powerful feature in NumPy that allows arrays with different shapes to be combined, enabling element-wise operations even when the arrays have different dimensions. This capability simplifies code and makes it more concise by eliminating the need for explicit looping structures. 
 
Basic Broadcasting Rules:

Broadcasting follows certain rules to determine how arrays with different shapes are treated during operations:

Rule 1: Dimensions Compatibility: If the arrays have a different number of dimensions, the shape of the smaller array is padded with ones on its left side to match the number of dimensions of the larger array.

Rule 2: Shape Compatibility: The dimensions of the two arrays are compared element-wise. Two dimensions are compatible when they are equal, or one of them is 1. If these conditions are not met, a ValueError is raised.

Rule 3: Size Compatibility: Arrays must have the same number of elements after broadcasting.

In [2]:
#Rule 1

import numpy as np

# Create arrays
arr1 = np.array([1, 2, 3])  # Shape: (3,)
arr2 = np.array([[10], [20], [30]])  # Shape: (3, 1)

# Perform element-wise addition
result = arr1 + arr2

print("arr1 shape:", arr1.shape)
print("arr2 shape:", arr2.shape)
print("Result shape:", result.shape)
print("Result array:\n", result)


arr1 shape: (3,)
arr2 shape: (3, 1)
Result shape: (3, 3)
Result array:
 [[11 12 13]
 [21 22 23]
 [31 32 33]]


In [3]:
#RULE 2

# Create arrays
arr3 = np.array([[1, 2, 3]])  # Shape: (1, 3)
arr4 = np.array([[10], [20]])  # Shape: (2, 1)

# Perform element-wise addition
result = arr3 + arr4

print("arr3 shape:", arr3.shape)
print("arr4 shape:", arr4.shape)
print("Result shape:", result.shape)
print("Result array:\n", result)


arr3 shape: (1, 3)
arr4 shape: (2, 1)
Result shape: (2, 3)
Result array:
 [[11 12 13]
 [21 22 23]]


In [4]:
#RULE 3

# Create arrays
arr5 = np.array([1, 2, 3])  # Shape: (3,)
arr6 = np.array([[10, 20, 30], [40, 50, 60]])  # Shape: (2, 3)

# Perform element-wise addition
result = arr5 + arr6

print("arr5 shape:", arr5.shape)
print("arr6 shape:", arr6.shape)
print("Result shape:", result.shape)
print("Result array:\n", result)


arr5 shape: (3,)
arr6 shape: (2, 3)
Result shape: (2, 3)
Result array:
 [[11 22 33]
 [41 52 63]]


# Array Iteration 

In [5]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Iterate through each element
for row in arr:
    for elem in row:
        print(elem)


1
2
3
4
5
6


In [6]:
# Applying a function to each element
arr_squared = np.square(arr)
print(arr_squared)


[[ 1  4  9]
 [16 25 36]]


In [7]:
# Compute the sum of each column
column_sums = np.sum(arr, axis=0)
print(column_sums)


[5 7 9]


In [8]:
# Using nditer to iterate over array elements
for elem in np.nditer(arr):
    print(elem)


1
2
3
4
5
6


# Array Sorting & Searching

In [9]:
import numpy as np

arr = np.array([[3, 2, 1],
                [6, 5, 4]])

sorted_arr = np.sort(arr)
print(sorted_arr)


[[1 2 3]
 [4 5 6]]


In [10]:
indices = np.argsort(arr)
print(indices)


[[2 1 0]
 [2 1 0]]


In [12]:
indices = np.where(arr > 3)
print(indices)

# np.where(), np.argmax(), and np.argmin() gives value of index

(array([1, 1, 1], dtype=int64), array([0, 1, 2], dtype=int64))


# MEMORY OPTIMIZATION

Memory Layout and Performance:
Understanding memory layout is important for optimizing performance, especially when working with large arrays. Here are a few points to consider:


Memory Contiguity: In row-major order, elements within the same row are contiguous in memory, while in column-major order, elements within the same column are contiguous.

Cache Efficiency: Accessing contiguous memory regions improves cache efficiency, which can lead to better performance.

Operations Performance: Certain operations may perform better with arrays stored in a particular memory layout. For example, matrix multiplication may benefit from column-major order.

1. Row-Major (C-style) Order:
In row-major order, also known as C-style order, elements of the array are stored row by row in memory. In a two-dimensional array, the elements of the first row are stored first, followed by the second row, and so on.

2. Column-Major (Fortran-style) Order:
In column-major order, also known as Fortran-style order, elements of the array are stored column by column in memory. In a two-dimensional array, the elements of the first column are stored first, followed by the second column, and so on.